version: '3.8'

services:

  mongodb:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
      - ./data/dblp.json:/data/db/dblp.json
    networks:
      - supernetwork

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - supernetwork

networks:
  supernetwork:
    name: supernetwork

volumes:
  mongodb-data:
    name : mongodb-data
