version: '3.8'

services:
    flask-app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 5000:5000
      depends_on:
        - mongo-db

        
    mongo-db:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass12345
      volumes:
        - ./dblp.json:/dblp.json
      ports:
        - 27017:27017